baseurl = "http://arvinsim.github.io/techblog"
languageCode = "en-us"
title = "Think Tech"

publishDir = "public"
layoutDir = "layouts"
contentDir = "content"

theme = "hugo-theme-mnmal"

[taxonomies]
    tag = "tags"
    language = "languages"
    platform = "platforms"
    articleType = "articleTypes"

[params]
    description = "Tech related Thoughts"
    author = "Arthur Vincent Simon"
    subtitle = "Tech, Thoughts, Talk"

