baseurl = "http://arvinsim.github.io/techblog"
languageCode = "en-us"
title = "Tech Blog"

publishDir = "../public"
layoutDir = "layouts"
contentDir = "content"

[taxonomies]
    tag = "tags"
    language = "languages"
    platform = "platforms"
    article-type = "article-types"

[params]
    description = "Tech related Thoughts"
    author = "Arthur Vincent Simon"
    subtitle = "Tech, Thought, Talk"

