baseurl = "http://arvinsim.github.io/techblog"
languageCode = "en-us"
title = "Thinker's Tech Tips"

publishDir = "public"
layoutDir = "layouts"
contentDir = "content"

theme = "hugo-theme-mnmal"

[taxonomies]
    tag = "tags"
    language = "languages"
    platform = "platforms"
    articleType = "articleTypes"

[params]
    description = "A web developer blog"
    author = "Arthur Vincent Simon"

